### ISSUE TITLE
Afirmações na seção explicativa do SAFe necessitam de referências e uma explicação mais elaborada

### ISSUE THREAD

**Issue by luanguimaraesla** [danielteles/Requisitos-2016.1#16]
Segundo o monitor, principalmente o primeiro parágrafo necessita de uma referência.  

Também me parece um pouco simples demais os dois parágrafos que são utilizados para explicar o que é o SAFe, acredito que pode-se fazer uma explicação objetiva mas que aborde alguns pontos de relevância para a escolha já nessa seção.

Exemplos:
- Buscar por referências;
- Citar alguns exemplos de empresas se sucesso;
- Citar vantagens e desvantagens do SAFe;
- Citar desafios de se utilizar o SAFe;
- Elaborar uma explicação breve sobre cada nível.

**Comment by luanguimaraesla** [comment]
Acabei o texto e já estpa no Drive, passando agora para o LaTeX.

**Comment by luanguimaraesla** [comment]
Terminei a implementação do novo texto explicativo no LaTeX, @Duerno pode revisar?

**Comment by Duerno** [comment]
Anexado
