### ISSUE TITLE
Elaborar um prefácio para a seção "Abordagem da ER"

### ISSUE THREAD

**Issue by luanguimaraesla** [danielteles/Requisitos-2016.1#4]
Para não ficar parecendo que apenas buscamos as referências e colocamos lá, acho que poderíamos, antes de citá-las, contextualizar a problemática do nosso ponto de vista e então, citar as fontes e a conclusão assim como já está lá.

Esse trabalho possui, nesta seção, algo como pensei: https://drive.google.com/open?id=0BybC770K-okDYW9CZGMzcU0tWXc

**Comment by danielteles** [comment]
Não entendi muito bem o que você propôs nessa _issue_, dei uma olhada no trabalho que citou e no nosso e achei bem semelhante.

**Comment by luanguimaraesla** [comment]
Vou dar uma lida amanhã pra relembrar qual era a proposta, fui acabar o trabalho de FSO que era pra entregar até meia noite só agora. Hehe, estou exausto.

**Comment by danielteles** [comment]
E aí?

**Comment by luanguimaraesla** [comment]
Caramba, tinha me esquecido disso, haha, depois que sair da aula de TEP vai ser só Req, vejo isso asim que chegar em casa.

**Comment by luanguimaraesla** [comment]
Dei uma olhada aqui, acho que já vou resolver essa issue.

**Comment by luanguimaraesla** [comment]
Pronto, terminei. O texto está no Drive devidamente modificado. Segui as dicas do João que estavam apenas no documento e reformulei todo o contexto das citações de forma que não ficassem tão disconectadas com o resto da seção.  
Já está dando 4h, vou dormir e hoje ainda de manhã eu passo rapidinho para o LaTeX e faço o merge request. Pra facilitar minha vida, @danielteles, tu podia revisar e aceitar o merge request #23 porque tem várias mudanças no documento da bibliografia.

**Comment by luanguimaraesla** [comment]
Melhorias implementadas
