### ISSUE TITLE
Planejamento da Primeira Iteração

### ISSUE THREAD

**Issue by luanguimaraesla** [danielteles/Requisitos-2016.1#41]
Ver com a professora quais serão as histórias de usuário que devem ser implementadas e então elaborar uma seção com os seguintes tópicos:

• Título;

• Valor de négocio, sendo classificado em 5 nivéis: Deve ter, ótimo, bom, médio e bom

ter, seu nível de importância é respectiva a ordem de apresentação, ou seja, deve ter

(mais importante) e bom ter (menos importante);

• Quem: Indicando o agente;

• O que: Indicando o que faz;

• Porque: Indicando o objetivo;

• Critérios de Aceitação: Indicando formas de usar a funcionalidade implementada em

uma história;

• Pontos: Indicando o grau de dificuldade de implementação da história.

**Comment by luanguimaraesla** [comment]
Repassando essa issue pra tu @danielteles

**Comment by danielteles** [comment]
de boa, vou fazer ela agora então
