### ISSUE TITLE
Sprint

### ISSUE THREAD

**Issue by danielteles** [danielteles/Requisitos-2016.1#44]
É necessário um capítulo descrevendo a sprint, falando do planejamento, execução, resultado e afins.

**Comment by danielteles** [comment]
@luanguimaraesla rola de tu escrever esse capítulo? A princípio é bem simples, e como tu que codou tudo acho que fica melhor se tu explicar essa parte.

**Comment by luanguimaraesla** [comment]
Não foi feito
