### ISSUE TITLE
Adicionar imagem explicativa do SAFe na seção de apresentação desse processo

### ISSUE THREAD

**Issue by luanguimaraesla** [danielteles/Requisitos-2016.1#5]
Não tem muito o que fazer nessa sessão, acho que já está boa, apenas, como fizeram nos outros trabalhos, poderíamos colocar aquela imagem do funcionamento do SAFe nessa sessão. Ela está no tópico "Processo da Engenharia de Requisitos". Acredito que ela pode vir para a presente seção e no lugar onde ela está atualmente existir apenas uma referência.

**Comment by danielteles** [comment]
Done
