### ISSUE TITLE
Elaboração da seção de explicação do RUP

### ISSUE THREAD

**Issue by luanguimaraesla** [danielteles/Requisitos-2016.1#6]
Pode segui o modelo do trabalho do Gabriel que está bem completo: https://drive.google.com/open?id=0BybC770K-okDYW9CZGMzcU0tWXc

**Comment by Duerno** [comment]
Já está feito? Alguém fez e não fechou a issue? kk

**Comment by luanguimaraesla** [comment]
Não. Veja a seção do SAFe que já está pronta, é para fazer algo semelhante naquele caminho que conversamos ontem.

**Comment by luanguimaraesla** [comment]
Vou fechar essa issue porque já está mapeada na issue #17 que está assinada para mim. @Duerno vou assinar outra issue pra você aqui no lugar dela.
